name: Deploy Dockerized App    #########@# This workflow deploys a Dockerized application to an EC2 instance using GitHub Actions.

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: nirajan-devops/ci-workflows/.github/workflows/cinew.yml@main
    with:
      image-name: wordpress-app
      container-name: wordpress-app
      port: "3000"
      container-port: "80"
    secrets:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
