name: WordPress Hello CI

on:
  push:
    branches: [ main ]   ####### ETrigger on push to main branch
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: nirajan-devops/ci-workflows/.github/workflows/wordpress.yml@main
    with:
      php-version: '8.2'
      wordpress-version: 'latest'
      test-command: 'composer test'