name: Deploy WordPress to EC2

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'docker-compose.yml'
      - '**.php'
      - '**.html'
      - '**.css'
      - '**.js'

jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      #- name: Upload project files to EC2
        #run: |
          #rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/wordpress-hello/

      - name: Install Docker and Run Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            sudo apt update -y
            sudo apt install -y docker.io curl
      
            # Install Docker Compose V2 plugin
            DOCKER_CONFIG=${HOME}/.docker
            mkdir -p $DOCKER_CONFIG/cli-plugins
            curl -SL https://github.com/docker/compose/releases/download/v2.24.4/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
            chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

            # Enable and start Docker
            sudo systemctl enable docker
            sudo systemctl start docker

            # Check Docker Compose version to confirm
            docker compose version

            # Go to the app directory and run containers
            cd /home/${{ secrets.USERNAME }}/wordpress-hello

            sudo docker compose down || true
            sudo docker compose up -d --build
          EOF
