name: Deploy WordPress to EC2

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/build.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy project files to EC2
        run: |
          scp -i ~/.ssh/id_rsa -r . ec2-user@${{ secrets.HOST }}:/home/ec2-user/wordpress-app

      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.HOST }} << 'EOF'
            cd wordpress-app
            docker compose down || true
            docker compose up -d --build
          EOF
